"""
Write a one-line Python generator or iterator expression that returns the infinite sequence of increasing integers
generated by repeatedly adding the ascii values of each letter in the word “Close” to itself.
67, 175, 286, 401, 502, 569, 677, 788, 903 is the beginning of this sequence.
Assume any needed Python standard library modules are already imported.
"""

import itertools

# ascii_generator = (ord("Close"[i % 5]) + i for i in itertools.count())

ascii_generator = (
    (1 + i // 5) * (sum([ord(c) for c in "Close"][: i % 5]))
    + (i // 5) * (sum([ord(c) for c in "Close"][i % 5:]))
    for i in itertools.count()
)
